# Generated by Django 3.1.2 on 2021-11-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_2', '0004_wordparams_control_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordparams',
            name='level_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordparams',
            name='level_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordparams',
            name='level_3',
            field=models.BooleanField(default=False),
        ),
    ]
