# Generated by Django 3.1.2 on 2021-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0002_auto_20210202_1733"),
    ]

    operations = [
        migrations.AddField(
            model_name="avto",
            name="bodyId",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
