# Generated by Django 3.1.2 on 2021-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20210721_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='heavy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='words',
            name='lesson',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
