# Generated by Django 3.1.2 on 2021-07-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_wordparams_lesson_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularVerbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=128)),
                ('past_simple', models.CharField(max_length=128)),
                ('past_participle', models.CharField(max_length=128)),
                ('russian', models.CharField(max_length=128)),
                ('learned', models.BooleanField(default=False)),
                ('heavy', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='wordparams',
            name='irregular_verbs',
            field=models.BooleanField(default=False),
        ),
    ]
