# Generated by Django 3.1.2 on 2021-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='irregular_verbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='words',
            name='phrasal_verbs',
            field=models.BooleanField(default=False),
        ),
    ]
