# Generated by Django 3.1.2 on 2021-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='info',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='words',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
