# Generated by Django 3.1.2 on 2021-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_wordparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordparams',
            name='lesson_0',
            field=models.BooleanField(default=False),
        ),
    ]
