# Generated by Django 3.1.2 on 2021-11-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("english", "0006_wordparams_english"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordparams",
            name="english",
        ),
    ]
