# Generated by Django 3.1.2 on 2021-11-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0009_words_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='control_list',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='words',
            name='heavy_list',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='words',
            name='learned_list',
            field=models.CharField(default='', max_length=256),
        ),
    ]
