# Generated by Django 3.1.2 on 2021-11-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("english", "0010_auto_20211110_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="words",
            name="phrasal_verbs",
            field=models.BooleanField(default=False, verbose_name="exam"),
        ),
    ]
