# Generated by Django 3.1.2 on 2022-03-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_auto_20211123_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='repeat_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='words',
            name='repeat_learn',
            field=models.IntegerField(default=3),
        ),
    ]
