# Generated by Django 3.1.2 on 2022-03-11 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0012_auto_20220310_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='control_list',
        ),
        migrations.AddField(
            model_name='words',
            name='control_list',
            field=models.ManyToManyField(related_name='user_control', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='words',
            name='heavy_list',
        ),
        migrations.AddField(
            model_name='words',
            name='heavy_list',
            field=models.ManyToManyField(related_name='user_heavy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='words',
            name='learned_list',
        ),
        migrations.AddField(
            model_name='words',
            name='learned_list',
            field=models.ManyToManyField(related_name='user_learned', to=settings.AUTH_USER_MODEL),
        ),
    ]
