# Generated by Django 3.1.2 on 2022-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0014_auto_20220314_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordparams',
            name='level_4',
            field=models.BooleanField(default=False),
        ),
    ]
