# Generated by Django 3.1.2 on 2022-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0015_wordparams_level_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='repeat_in_progress',
            new_name='important',
        ),
        migrations.AddField(
            model_name='wordparams',
            name='only_important_words',
            field=models.BooleanField(default=False),
        ),
    ]
