# Generated by Django 3.1.2 on 2022-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_auto_20220519_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordparams',
            name='level_5',
            field=models.BooleanField(default=False),
        ),
    ]
