# Generated by Django 3.1.2 on 2020-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
