# Generated by Django 3.1.2 on 2020-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Christmas",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_state", models.DateTimeField()),
                ("general", models.BooleanField(default=False)),
                ("first_line", models.BooleanField(default=False)),
                ("second_line", models.BooleanField(default=False)),
                ("third_line", models.BooleanField(default=False)),
            ],
        ),
    ]
