# Generated by Django 3.1.2 on 2020-11-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_christmas"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Christmas",
        ),
    ]
