# Generated by Django 3.1.2 on 2020-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logs_temp1_weatherrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrain',
            name='snow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatherrain',
            name='temp_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatherrain',
            name='temp_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherrain',
            name='rain',
            field=models.IntegerField(default=0),
        ),
    ]
