# Generated by Django 3.1.2 on 2022-06-02 13:23

from django.db import migrations


def add_new_settings(apps, _):
    Setting = apps.get_model("core", "Setting")
    regular = Setting(controller_name="regular",
                       value=1,
                       label="Включение и отключение регулярных функция по рассписанию")
    Setting.objects.bulk_create((regular,))


def dell_regular(apps, _):
    Setting = apps.get_model("core", "Setting")
    regular = Setting.objects.get(controller_name="regular")
    regular.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_avto_link_car'),
    ]

    operations = [

        migrations.RunPython(add_new_settings, dell_regular),

    ]
